name: Test EC2 Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "WanderLust Connected to EC2 successfully!"
            echo "Current user:"
            whoami

            echo "Current directory:"
            pwd

            echo "Server:"
            hostname